def assertion_fail():
    return 2 + 2 == 4